import 'package:fl_clash/hgfast/transport/e2ee.dart' as e2ee;
import 'package:fl_clash/hgfast/transport/primitives.dart' as primitives;
import 'package:flutter_test/flutter_test.dart';

// Golden vectors generated by re-running the deployed backend's own
// app/core/client_api/lib/e2ee.js against fixed X25519 test keys, so a
// mismatch here means the Dart port has drifted from the server, not that
// the fixture is wrong.
const String _clientEphPrivRawB64 = 'UPKKxhT9oHEbuZ3xLJA7fugVZwPvImoOyXn9WwUy0WQ=';
const String _serverEphPubRawB64 = 'IdHs93HkVysPB0GDl701zyAGJrKkyUyWksHtwkzlDnI=';
const String _saltB64 = 'MzMzMzMzMzMzMzMzMzMzMw==';
const String _sessionKeyB64 = 'IxJPTyUaJ4g3nzLdE+2wRE916g1sgN+Mv6hXKm2r4ds=';

const Map<String, Object?> _sealedBlob = <String, Object?>{
  'session_key_id': 'skid-1',
  'aead_nonce': 'AAAABwAAAAAAAAAB',
  'ciphertext':
      '3HyHXlT92Cfpo1yjVRYhybIGyk7Hq9u5xaw29NWYr9B+sePm8nyW2ayPNWt5h/Mf9g==',
  'aad':
      'eyJhcHBfaWQiOiJoZ2Zhc3QiLCJjaGFubmVsIjoic3RhYmxlIiwiZXhwaXJlc19hdCI6MTc1NTMwMjQ5MCwiaXNzdWVkX2F0IjoxNzU1MzAyNDAwLCJub25jZSI6Im5vbmNlLWUyZWUtMSIsInB1cnBvc2UiOiJIR0ZBU1QtQy1SRVNQT05TRS0vYXBpL2NsaWVudC9hbmRyb2lkL3YxL3RyYWZmaWMtdjEiLCJyZXF1ZXN0X2hhc2giOiJhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhIiwic2Vzc2lvbl9pZCI6InNlc3MtMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMmJiIiwic2Vzc2lvbl9rZXlfaWQiOiJza2lkLTEiLCJ1c2VyX2lkIjo0M30=',
};

void main() {
  test('deriveSessionKeyClient matches the server golden vector', () async {
    final clientEphKeyPair = await primitives.x25519KeyPairFromSeed(
      primitives.fromBase64(_clientEphPrivRawB64),
    );
    final sessionKey = await e2ee.deriveSessionKeyClient(
      clientEphemeralKeyPair: clientEphKeyPair,
      serverEphemeralPublicKeyRaw: primitives.fromBase64(_serverEphPubRawB64),
      salt: primitives.fromBase64(_saltB64),
    );
    expect(primitives.toBase64(sessionKey), _sessionKeyB64);
  });

  test('openResponse decrypts a sealed blob against its AAD context', () async {
    final sessionKey = primitives.fromBase64(_sessionKeyB64);
    final expectedAad = <String, Object?>{
      'app_id': 'hgfast',
      'channel': 'stable',
      'expires_at': 1755302490,
      'issued_at': 1755302400,
      'nonce': 'nonce-e2ee-1',
      'purpose': 'HGFAST-C-RESPONSE-/api/client/android/v1/traffic-v1',
      'request_hash':
          'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'session_id': 'sess-2222222222222222222222222222bb',
      'session_key_id': 'skid-1',
      'user_id': 43,
    };
    final body = await e2ee.openResponse(
      sessionKey: sessionKey,
      blob: _sealedBlob,
      expectedAad: expectedAad,
    );
    expect(body, <String, Object?>{
      'traffic': <String, Object?>{'up': 100, 'down': 200},
    });
  });

  test('openResponse rejects a mismatched AAD context', () async {
    final sessionKey = primitives.fromBase64(_sessionKeyB64);
    final wrongAad = <String, Object?>{
      'app_id': 'hgfast',
      'channel': 'stable',
      'expires_at': 1755302490,
      'issued_at': 1755302400,
      'nonce': 'nonce-e2ee-1',
      'purpose': 'HGFAST-C-RESPONSE-/api/client/android/v1/traffic-v1',
      'request_hash':
          'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'session_id': 'sess-2222222222222222222222222222bb',
      'session_key_id': 'skid-1',
      'user_id': 999,
    };
    expect(
      () => e2ee.openResponse(
        sessionKey: sessionKey,
        blob: _sealedBlob,
        expectedAad: wrongAad,
      ),
      throwsA(isA<e2ee.HgfastE2eeOpenException>()),
    );
  });
}
