import 'dart:convert';

import 'package:fl_clash/hgfast/transport/reqsign.dart' as reqsign;
import 'package:flutter_test/flutter_test.dart';

// Golden vectors generated by re-running the deployed backend's own
// app/core/client_api/lib/{jcs,reqsign}.js against fixed inputs, so a
// mismatch here means the Dart port has drifted from the server, not that
// the fixture is wrong.
void main() {
  test('canonicalUri sorts query keys and percent-encodes like encodeURIComponent', () {
    final uri = reqsign.canonicalUri(
      '/api/client/android/v1/nodes',
      <String, String>{'b': '2', 'a': '1'},
    );
    expect(uri, '/api/client/android/v1/nodes?a=1&b=2');
  });

  test('canonicalUri with no query returns the bare pathname', () {
    expect(reqsign.canonicalUri('/api/client/android/v1/time'), '/api/client/android/v1/time');
  });

  test('sign matches the server golden vector', () {
    final signature = reqsign.sign(
      method: 'GET',
      canonUri: '/api/client/android/v1/nodes?a=1&b=2',
      nonce: 'nonce-abc-123',
      timestamp: '1755302400',
      body: utf8.encode(''),
    );
    expect(
      signature,
      'f78afbbe9e065874351f8bcc866574af9171b0511153fe0b5d9fd11564fdbf31',
    );
  });

  test('requestHash matches the server golden vector', () {
    final hash = reqsign.requestHash(
      method: 'GET',
      canonUri: '/api/client/android/v1/nodes?a=1&b=2',
      nonce: 'nonce-abc-123',
      timestamp: '1755302400',
      body: utf8.encode(''),
      deviceId: 'deadbeefcafef00d',
      token:
          'ct-testtoken0000000000000000000000000000000000000000000000000000',
    );
    expect(
      hash,
      'fa2ed950a26c1385743156749230969f12625773c322f85cb07027445adb8e9d',
    );
  });

  test('buildRequestHeaders derives sign and request_hash from the same canonical string', () {
    final headers = reqsign.buildRequestHeaders(
      method: 'GET',
      pathname: '/api/client/android/v1/nodes',
      query: <String, String>{'b': '2', 'a': '1'},
      body: utf8.encode(''),
      nonce: 'nonce-abc-123',
      timestamp: '1755302400',
      deviceId: 'deadbeefcafef00d',
      token:
          'ct-testtoken0000000000000000000000000000000000000000000000000000',
    );
    expect(
      headers.signature,
      'f78afbbe9e065874351f8bcc866574af9171b0511153fe0b5d9fd11564fdbf31',
    );
    expect(
      headers.requestHash,
      'fa2ed950a26c1385743156749230969f12625773c322f85cb07027445adb8e9d',
    );
    expect(headers.toHeaders()['X-HG-Device'], 'deadbeefcafef00d');
  });
}
