import 'package:fl_clash/hgfast/transport/primitives.dart' as primitives;
import 'package:fl_clash/hgfast/transport/respwrap.dart' as respwrap;
import 'package:flutter_test/flutter_test.dart';

// Golden vectors generated by re-running the deployed backend's own
// app/core/client_api/lib/respwrap.js against a synthetic test-only root
// keypair (not a real HGFAST production root), so a mismatch here means the
// Dart port has drifted from the server's response verifier, not that the
// fixture is wrong.
const String _rootPubB64 = '0EqyMnQrtKs6E2i9RhXk5tAiSrcaAWuvhSCjMsl3hzc=';
const int _rootEpoch = 1;

final Map<String, Object?> _cert = <String, Object?>{
  'v': 'HGFAST-SUBKEY-CERT-v1',
  'key_id': 'k1',
  'subkey_pub': 'oJql9HpnWYAv+VX43C0qFKXJnSO+l/hkEn/5ODRVpPA=',
  'usage': 'C_RESPONSE',
  'valid_from_epoch': 1,
  'valid_to_epoch': 10,
  'root_sig':
      '/5FvOQiSLzY5sSMwtSepkUViw71U2oq89qghtWVYk5QwcR6X6oZ9mvVH1aB2sytvQNi+Pv/tUMQ71fjp0UoJBg==',
};

final Map<String, Object?> _plainResponse = <String, Object?>{
  'envelope': <String, Object?>{
    'purpose': 'HGFAST-C-RESPONSE-/api/client/android/v1/nodes-v1',
    'user_id': 42,
    'session_id': 'sess-1111111111111111111111111111aa',
    'request_hash':
        'fa2ed950a26c1385743156749230969f12625773c322f85cb07027445adb8e9d',
    'nonce': 'nonce-abc-123',
    'issued_at': 1755302400,
    'expires_at': 1755302490,
    'body_hash':
        '4175ff21995d2b78da03dcb3eddb72703d45f02b0e6ff1dfdd3d05ff20173856',
    'schema_version': 1,
    'app_id': 'hgfast',
    'channel': 'stable',
    'platform': 'android',
  },
  'body_jcs': '{"nodes":[{"name":"hk-01","server":"1.2.3.4"}]}',
  'sig':
      'RxKrZmnBw/46j+DlxHrDNK53v3UJzuRqnVDPpoxft8LnVK+ZpTPgbtKFOO+MhHq8F8luou2zNeTdgUR8k2sICQ==',
  'cert': _cert,
};

final Map<String, Object?> _sealedResponse = <String, Object?>{
  'envelope': <String, Object?>{
    'purpose': 'HGFAST-C-RESPONSE-/api/client/android/v1/traffic-v1',
    'user_id': 43,
    'session_id': 'sess-2222222222222222222222222222bb',
    'request_hash':
        'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    'nonce': 'nonce-e2ee-1',
    'issued_at': 1755302400,
    'expires_at': 1755302490,
    'body_hash':
        'aa1ae289a863c5bfb0fb02f2fdf5aae9b0a66b8c2c950cda26e358f69c59a5d1',
    'schema_version': 1,
    'app_id': 'hgfast',
    'channel': 'stable',
    'platform': 'android',
  },
  'body_jcs':
      '{"aad":"eyJhcHBfaWQiOiJoZ2Zhc3QiLCJjaGFubmVsIjoic3RhYmxlIiwiZXhwaXJlc19hdCI6MTc1NTMwMjQ5MCwiaXNzdWVkX2F0IjoxNzU1MzAyNDAwLCJub25jZSI6Im5vbmNlLWUyZWUtMSIsInB1cnBvc2UiOiJIR0ZBU1QtQy1SRVNQT05TRS0vYXBpL2NsaWVudC9hbmRyb2lkL3YxL3RyYWZmaWMtdjEiLCJyZXF1ZXN0X2hhc2giOiJhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhIiwic2Vzc2lvbl9pZCI6InNlc3MtMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMmJiIiwic2Vzc2lvbl9rZXlfaWQiOiJza2lkLTEiLCJ1c2VyX2lkIjo0M30=","aead_nonce":"AAAABwAAAAAAAAAB","ciphertext":"3HyHXlT92Cfpo1yjVRYhybIGyk7Hq9u5xaw29NWYr9B+sePm8nyW2ayPNWt5h/Mf9g==","session_key_id":"skid-1"}',
  'sig':
      'djITiWS+oozEfKucM0Jjmihcfuh4LHezGh/YopCGcTTD8CuYq8NgA9UE3j1pazNPHSIdLP+/2XL4OW2WgHwpCA==',
  'cert': _cert,
};

const String _sealedSessionKeyB64 = 'IxJPTyUaJ4g3nzLdE+2wRE916g1sgN+Mv6hXKm2r4ds=';

void main() {
  final rootKeys = <List<int>>[primitives.fromBase64(_rootPubB64)];

  test('verifySignedResponse accepts a plain envelope and returns its body', () async {
    final result = await respwrap.verifySignedResponse(
      response: _plainResponse,
      rootPublicKeys: rootKeys,
      rootEpoch: _rootEpoch,
      expect: const respwrap.SignedResponseExpectation(
        userId: 42,
        sessionId: 'sess-1111111111111111111111111111aa',
        requestHash:
            'fa2ed950a26c1385743156749230969f12625773c322f85cb07027445adb8e9d',
        nonce: 'nonce-abc-123',
        now: 1755302450,
      ),
    );
    expect(result, isA<respwrap.SignedResponseOk>());
    final ok = result as respwrap.SignedResponseOk;
    expect(ok.isSealed, isFalse);
    expect(ok.body, <String, Object?>{
      'nodes': <Object?>[
        <String, Object?>{'name': 'hk-01', 'server': '1.2.3.4'},
      ],
    });
  });

  test('verifySignedResponse rejects an expired envelope', () async {
    final result = await respwrap.verifySignedResponse(
      response: _plainResponse,
      rootPublicKeys: rootKeys,
      rootEpoch: _rootEpoch,
      expect: const respwrap.SignedResponseExpectation(
        userId: 42,
        sessionId: 'sess-1111111111111111111111111111aa',
        requestHash:
            'fa2ed950a26c1385743156749230969f12625773c322f85cb07027445adb8e9d',
        nonce: 'nonce-abc-123',
        now: 1755400000,
      ),
    );
    expect(result, isA<respwrap.SignedResponseFailed>());
    expect((result as respwrap.SignedResponseFailed).error, 'Expired');
  });

  test('verifySignedResponse rejects a session_id that does not match the request', () async {
    final result = await respwrap.verifySignedResponse(
      response: _plainResponse,
      rootPublicKeys: rootKeys,
      rootEpoch: _rootEpoch,
      expect: const respwrap.SignedResponseExpectation(
        userId: 42,
        sessionId: 'sess-wrong',
        requestHash:
            'fa2ed950a26c1385743156749230969f12625773c322f85cb07027445adb8e9d',
        nonce: 'nonce-abc-123',
        now: 1755302450,
      ),
    );
    expect((result as respwrap.SignedResponseFailed).error, 'SessionMismatch');
  });

  test('verifySignedResponse decrypts a sealed E2EE body given the session key', () async {
    final result = await respwrap.verifySignedResponse(
      response: _sealedResponse,
      rootPublicKeys: rootKeys,
      rootEpoch: _rootEpoch,
      expect: const respwrap.SignedResponseExpectation(
        userId: 43,
        sessionId: 'sess-2222222222222222222222222222bb',
        requestHash:
            'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
        nonce: 'nonce-e2ee-1',
        now: 1755302450,
      ),
      sessionKey: primitives.fromBase64(_sealedSessionKeyB64),
    );
    expect(result, isA<respwrap.SignedResponseOk>());
    final ok = result as respwrap.SignedResponseOk;
    expect(ok.isSealed, isTrue);
    expect(ok.body, <String, Object?>{
      'traffic': <String, Object?>{'up': 100, 'down': 200},
    });
  });

  test('verifySignedResponse fails closed when a sealed body has no session key', () async {
    final result = await respwrap.verifySignedResponse(
      response: _sealedResponse,
      rootPublicKeys: rootKeys,
      rootEpoch: _rootEpoch,
      expect: const respwrap.SignedResponseExpectation(
        userId: 43,
        sessionId: 'sess-2222222222222222222222222222bb',
        requestHash:
            'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
        nonce: 'nonce-e2ee-1',
        now: 1755302450,
      ),
    );
    expect((result as respwrap.SignedResponseFailed).error, 'E2EEKeyMissing');
  });

  test('verifySignedResponse fails closed instead of throwing on a non-int issued_at', () async {
    final malformed = <String, Object?>{
      'envelope': <String, Object?>{
        ..._plainResponse['envelope'] as Map<String, Object?>,
        'issued_at': 'not-a-number',
      },
      'body_jcs': _plainResponse['body_jcs'],
      'sig': _plainResponse['sig'],
      'cert': _cert,
    };
    final result = await respwrap.verifySignedResponse(
      response: malformed,
      rootPublicKeys: rootKeys,
      rootEpoch: _rootEpoch,
      expect: const respwrap.SignedResponseExpectation(
        userId: 42,
        sessionId: 'sess-1111111111111111111111111111aa',
        requestHash:
            'fa2ed950a26c1385743156749230969f12625773c322f85cb07027445adb8e9d',
        nonce: 'nonce-abc-123',
        now: 1755302450,
      ),
    );
    expect(
      (result as respwrap.SignedResponseFailed).error,
      'MalformedResponse',
    );
  });

  test('verifySignedResponse fails closed instead of throwing on a non-string body_jcs', () async {
    final malformed = <String, Object?>{
      'envelope': _plainResponse['envelope'],
      'body_jcs': 12345,
      'sig': _plainResponse['sig'],
      'cert': _cert,
    };
    final result = await respwrap.verifySignedResponse(
      response: malformed,
      rootPublicKeys: rootKeys,
      rootEpoch: _rootEpoch,
      expect: const respwrap.SignedResponseExpectation(
        userId: 42,
        sessionId: 'sess-1111111111111111111111111111aa',
        requestHash:
            'fa2ed950a26c1385743156749230969f12625773c322f85cb07027445adb8e9d',
        nonce: 'nonce-abc-123',
        now: 1755302450,
      ),
    );
    expect(
      (result as respwrap.SignedResponseFailed).error,
      'MalformedResponse',
    );
  });

  test('verifySignedResponse fails closed instead of throwing when envelope is not a map', () async {
    final malformed = <String, Object?>{
      'envelope': 'not-a-map',
      'body_jcs': _plainResponse['body_jcs'],
      'sig': _plainResponse['sig'],
      'cert': _cert,
    };
    final result = await respwrap.verifySignedResponse(
      response: malformed,
      rootPublicKeys: rootKeys,
      rootEpoch: _rootEpoch,
      expect: const respwrap.SignedResponseExpectation(
        userId: 42,
        sessionId: 'sess-1111111111111111111111111111aa',
        requestHash:
            'fa2ed950a26c1385743156749230969f12625773c322f85cb07027445adb8e9d',
        nonce: 'nonce-abc-123',
        now: 1755302450,
      ),
    );
    expect(
      (result as respwrap.SignedResponseFailed).error,
      'MalformedResponse',
    );
  });
}
