import 'package:fl_clash/hgfast/transport/primitives.dart' as primitives;
import 'package:fl_clash/hgfast/transport/signing.dart' as signing;
import 'package:flutter_test/flutter_test.dart';

// Golden vectors generated by re-running the deployed backend's own
// app/core/client_api/lib/signing.js against a synthetic test-only root
// keypair (not a real HGFAST production root), so a mismatch here means the
// Dart port has drifted from the server's C.2 verifier, not that the
// fixture is wrong.
const String _rootPubB64 = '0EqyMnQrtKs6E2i9RhXk5tAiSrcaAWuvhSCjMsl3hzc=';
const int _rootEpoch = 1;

final Map<String, Object?> _cert = <String, Object?>{
  'v': 'HGFAST-SUBKEY-CERT-v1',
  'key_id': 'k1',
  'subkey_pub': 'oJql9HpnWYAv+VX43C0qFKXJnSO+l/hkEn/5ODRVpPA=',
  'usage': 'C_RESPONSE',
  'valid_from_epoch': 1,
  'valid_to_epoch': 10,
  'root_sig':
      '/5FvOQiSLzY5sSMwtSepkUViw71U2oq89qghtWVYk5QwcR6X6oZ9mvVH1aB2sytvQNi+Pv/tUMQ71fjp0UoJBg==',
};

final Map<String, Object?> _envelope = <String, Object?>{
  'purpose': 'HGFAST-C-RESPONSE-/api/client/android/v1/nodes-v1',
  'user_id': 42,
  'session_id': 'sess-1111111111111111111111111111aa',
  'request_hash':
      'fa2ed950a26c1385743156749230969f12625773c322f85cb07027445adb8e9d',
  'nonce': 'nonce-abc-123',
  'issued_at': 1755302400,
  'expires_at': 1755302490,
  'body_hash':
      '4175ff21995d2b78da03dcb3eddb72703d45f02b0e6ff1dfdd3d05ff20173856',
  'schema_version': 1,
  'app_id': 'hgfast',
  'channel': 'stable',
  'platform': 'android',
};

const String _envelopeSig =
    'RxKrZmnBw/46j+DlxHrDNK53v3UJzuRqnVDPpoxft8LnVK+ZpTPgbtKFOO+MhHq8F8luou2zNeTdgUR8k2sICQ==';

void main() {
  final rootKey = primitives.fromBase64(_rootPubB64);

  test('verifyCert accepts a cert signed by an embedded root at a valid epoch', () async {
    final result = await signing.verifyCert(
      cert: _cert,
      rootPublicKeys: <List<int>>[rootKey],
      rootEpoch: _rootEpoch,
    );
    expect(result.isOk, isTrue);
  });

  test('verifyCert rejects an epoch outside the cert validity window', () async {
    final result = await signing.verifyCert(
      cert: _cert,
      rootPublicKeys: <List<int>>[rootKey],
      rootEpoch: 99,
    );
    expect(result.error, 'CertEpochInvalid');
  });

  test('verifyCert rejects when no embedded root key matches', () async {
    final result = await signing.verifyCert(
      cert: _cert,
      rootPublicKeys: <List<int>>[_zeroKey32],
      rootEpoch: _rootEpoch,
    );
    expect(result.error, 'BadSubkeyCert');
  });

  test('verifyCert rejects a tampered cert field', () async {
    final tampered = Map<String, Object?>.from(_cert);
    tampered['key_id'] = 'k2';
    final result = await signing.verifyCert(
      cert: tampered,
      rootPublicKeys: <List<int>>[rootKey],
      rootEpoch: _rootEpoch,
    );
    expect(result.error, 'BadSubkeyCert');
  });

  test('verifyEnvelope accepts a matching C_RESPONSE envelope and signature', () async {
    final result = await signing.verifyEnvelope(
      envelope: _envelope,
      signatureBase64: _envelopeSig,
      cert: _cert,
      rootPublicKeys: <List<int>>[rootKey],
      rootEpoch: _rootEpoch,
    );
    expect(result.isOk, isTrue);
  });

  test('verifyEnvelope rejects a cert whose usage is not C_RESPONSE', () async {
    final wrongUsageCert = Map<String, Object?>.from(_cert);
    wrongUsageCert['usage'] = 'B_CONFIG';
    final result = await signing.verifyEnvelope(
      envelope: _envelope,
      signatureBase64: _envelopeSig,
      cert: wrongUsageCert,
      rootPublicKeys: <List<int>>[rootKey],
      rootEpoch: _rootEpoch,
    );
    expect(result.error, 'KeyUsageMismatch');
  });

  test('verifyEnvelope rejects a tampered envelope field', () async {
    final tampered = Map<String, Object?>.from(_envelope);
    tampered['user_id'] = 43;
    final result = await signing.verifyEnvelope(
      envelope: tampered,
      signatureBase64: _envelopeSig,
      cert: _cert,
      rootPublicKeys: <List<int>>[rootKey],
      rootEpoch: _rootEpoch,
    );
    expect(result.error, 'BadSignature');
  });

  test('verifyCert rejects an unpinned cert version string', () async {
    final wrongVersion = Map<String, Object?>.from(_cert);
    wrongVersion['v'] = 'HGFAST-SUBKEY-CERT-v2';
    final result = await signing.verifyCert(
      cert: wrongVersion,
      rootPublicKeys: <List<int>>[rootKey],
      rootEpoch: _rootEpoch,
    );
    expect(result.error, 'BadCertVersion');
  });

  test('verifyCert fails closed instead of throwing on non-int epoch fields', () async {
    final malformed = Map<String, Object?>.from(_cert);
    malformed['valid_from_epoch'] = 'not-a-number';
    final result = await signing.verifyCert(
      cert: malformed,
      rootPublicKeys: <List<int>>[rootKey],
      rootEpoch: _rootEpoch,
    );
    expect(result.error, 'MalformedCert');
  });

  test('verifyCert fails closed instead of throwing on non-base64 root_sig', () async {
    final malformed = Map<String, Object?>.from(_cert);
    malformed['root_sig'] = 'not valid base64!!';
    final result = await signing.verifyCert(
      cert: malformed,
      rootPublicKeys: <List<int>>[rootKey],
      rootEpoch: _rootEpoch,
    );
    expect(result.error, 'MalformedCert');
  });

  test('verifyEnvelope fails closed instead of throwing when subkey_pub is removed from the cert', () async {
    // subkey_pub is itself part of the cert's own signed content
    // (_certSigningObject), so removing it changes what verifyCert
    // re-hashes and is caught there as BadSubkeyCert, before verifyEnvelope
    // ever reaches its own subkey_pub decode guard. Either way, no throw.
    final malformed = Map<String, Object?>.from(_cert);
    malformed.remove('subkey_pub');
    final result = await signing.verifyEnvelope(
      envelope: _envelope,
      signatureBase64: _envelopeSig,
      cert: malformed,
      rootPublicKeys: <List<int>>[rootKey],
      rootEpoch: _rootEpoch,
    );
    expect(result.error, 'BadSubkeyCert');
  });

  test('verifyEnvelope fails closed instead of throwing on non-base64 signatureBase64', () async {
    final result = await signing.verifyEnvelope(
      envelope: _envelope,
      signatureBase64: 'not valid base64!!',
      cert: _cert,
      rootPublicKeys: <List<int>>[rootKey],
      rootEpoch: _rootEpoch,
    );
    expect(result.error, 'MalformedSignature');
  });

  test('verifyObject fails closed instead of throwing on a missing subkey_sig', () async {
    final objWithoutSig = <String, Object?>{'object_version': 1};
    final result = await signing.verifyObject(
      obj: objWithoutSig,
      cert: _cert,
      rootPublicKeys: <List<int>>[rootKey],
      rootEpoch: _rootEpoch,
      expectedUsage: 'C_RESPONSE',
    );
    expect(result.error, 'MalformedObject');
  });
}

final List<int> _zeroKey32 = List<int>.filled(32, 0);
